/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package thrifty;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;


/**
 *
 * @author User
 */

public class Dashboard extends javax.swing.JFrame {
   
    public static HashMap<String, List<ProductDTO>> allProducts;
    public static ObjectMapper mapper = new ObjectMapper();
    public static File file = new File("src\\thrifty\\products.json");
    public static List<ProductDTO> uniqueProductList;
    
    public Dashboard()  {
       
        try {
            initComponents();
            
            navBar1.setDB(this);
            
            allProducts = mapper.readValue(file, new TypeReference<HashMap<String, List<ProductDTO>>>() {});
            
            for (ProductDTO data : allProducts.get("eraser")){
                System.out.println(data.getName());
                System.out.println(data.getPrice());
                System.out.println(data.getStore());
            }
            
            for (String name : allProducts.keySet()){
                for(ProductDTO data : allProducts.get(name)){
                    System.out.println(data.getName() + " " + data.getId());
                }
                    
            }
            
        } catch (IOException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            
          
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    public void shop(){
        tabs.setSelectedIndex(0);
    }
    
    public void dashboard(){
        tabs.setSelectedIndex(1);
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        navBar1 = new thrifty.NavBar();
        tabs = new javax.swing.JTabbedPane();
        shopOverview2 = new thrifty.ShopOverview();
        productPanel2 = new thrifty.ProductPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 900));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 900));

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setLayer(navBar1, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(navBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        tabs.setPreferredSize(new java.awt.Dimension(1280, 800));
        tabs.addTab("tab1", shopOverview2);
        tabs.addTab("tab2", productPanel2);

        jLayeredPane1.add(tabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 710));

        getContentPane().add(jLayeredPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private thrifty.NavBar navBar1;
    private thrifty.ProductPanel productPanel2;
    private thrifty.ShopOverview shopOverview2;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
