/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package thrifty;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import com.fasterxml.jackson.annotation.*;
/**
 *
 * @author User
 */
public class Product extends javax.swing.JPanel {

    /**
     * Creates new form Product
     */
    private String Name;
    private String Location;
    private double Price;
    private String image;
    private String shopName;
    private String description;
    private String quantity;
    private Dashboard db;
     private ProductDTO product;
     private ShopDTO shop;
    public static void icon(String path, JLabel component,int width, int height){
        ImageIcon imageIcon =  new ImageIcon(path);
        Image img = imageIcon.getImage();
        Image imageScaled = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imageScaled);
        component.setIcon(scaledIcon);
        
    }
    
    public Product() {
        initComponents();
    }
    
    public Product(String Name, String Location, double Price, String image){
        initComponents();
        this.Location = Location;
        this.Name = Name;
        this.Price = Price;
        
        // Change default values
        Name = toTitleCase(Name);
        this.name.setText(Name);
        this.location.setText(Location);
        this.price.setText("PHP"+ String.format("%.2f", Price));
        icon(image,picture,158,104);
        
    }
    
    public Product(String Name, String Location, double Price,String shopName, String image, String description, int quantity, Dashboard db, ProductDTO product,ShopDTO shop){
        initComponents();
        this.Location = Location;
        this.Name = Name;
        this.Price = Price;
        this.shopName = shopName;
        
        // Change default values
        this.image = image;
        Name = toTitleCase(Name);
        this.name.setText(Name);
        this.location.setText(Location);
        this.price.setText("PHP"+ String.format("%.2f", Price));
        this.shopNameInput.setText(shopName);
        icon(image,picture,158,104);
        this.description = description;
        String tempQuantity = String.valueOf(quantity);
        this.quantity = tempQuantity;
        this.db = db;
        this.product = product;
        this.shop = shop;
        
    }
    
    public Product(String Name, double Price,String shopName, String image, String description, int quantity, Dashboard db, ProductDTO product,ShopDTO shop){
        initComponents();
        
        this.Name = Name;
        this.Price = Price;
        this.shopName = shopName;
        
        
        // Change default values
        this.image = image;
        Name = toTitleCase(Name);
        this.name.setText(Name);
        this.location.setText(Location);
        this.price.setText("PHP"+ String.format("%.2f", Price));
        this.shopNameInput.setText(shopName);
        icon(image,picture,158,104);
        this.description = description;
        String tempQuantity = String.valueOf(quantity);
        this.quantity = tempQuantity;
        this.db = db;
        this.product = product;
        this.shop = shop;
        this.Location = db.getLocation(product.getStoreID());
        
    }
   
   public static String toTitleCase(String input) {
        if (input == null || input.isEmpty()) {
            return input; // Return null or empty string as is
        }

        String[] words = input.split(" "); // Split the string by spaces
        StringBuilder titleCaseString = new StringBuilder();

        for (String word : words) {
            if (word.length() > 0) {
                // Capitalize the first letter and append the rest of the word
                titleCaseString.append(Character.toUpperCase(word.charAt(0)))
                                .append(word.substring(1).toLowerCase())
                                .append(" "); // Append a space
            }
        }
        return titleCaseString.toString().trim();
   }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shopNameInput = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        picture = new javax.swing.JLabel();
        location = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        shopNameInput.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        shopNameInput.setText("location");

        name.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        name.setText("item name");

        price.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        price.setText("Price");

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        jPanel1.setPreferredSize(new java.awt.Dimension(158, 104));
        jPanel1.setLayout(new java.awt.BorderLayout());

        picture.setPreferredSize(new java.awt.Dimension(158, 104));
        jPanel1.add(picture, java.awt.BorderLayout.CENTER);

        location.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        location.setText("location");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(location, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(price, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shopNameInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(shopNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        //public ProductViewPanel(String name, String price, String quantity, String description, String pictureIMG, Dashboard db) {
        //private String Name;
//    private String Location;
//    private double Price;
//    private String image;
//    private String shopName;
        String price1 = ("₱" + String.format("%.2f", Price));
        
        ProductViewPanel view = new ProductViewPanel(Name,price1,quantity,description,image,db,product,shop);
        db.viewProduct(view);
    }//GEN-LAST:event_formMouseClicked
    /*
    private String Name;
    private String Location;
    private double Price;
    private String image;
    private String shopName;
    private String description;
    private String quantity;
    private Dashboard db;
     private ProductDTO product;
    */
    //Product individualProduct = new Product(product.getName(),location,product.getPrice(),product.getStore(),product.getImage(),product.getDescription(),product.getQuantity(),this,product);
    public int getPrice(){
        return (int)Price;
    }
    
    public String getName(){
        return Name;
    }
   
    public String getStore(){
        return shopName;
    }
    
    public String getImage(){
        return image;
    }
    public String getDescription(){
        return description;
    }
    public int getQuantity(){
        return Integer.valueOf(quantity);
    }
    public ProductDTO getProduct(){
        return product;
    }
    public String getStoreID(){
        return product.getStoreID();
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel location;
    public javax.swing.JLabel name;
    private javax.swing.JLabel picture;
    public javax.swing.JLabel price;
    public javax.swing.JLabel shopNameInput;
    // End of variables declaration//GEN-END:variables
}
