/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package thrifty;

import java.util.HashMap;
import java.util.Set;

/**
 *
 * @author User
 */
public class ShopOverview extends javax.swing.JPanel {

    /** Creates new form ShopOverview */
    HashMap<String, HashMap<String, ProductDTO>> allProducts;
    ShopDTO shop;
    HashMap<String,ShopDTO> allShops;
    UserDTO user;
    Dashboard db;
    
    public ShopOverview() {
        initComponents();
        
        sidebar1.setShopOverview(this);
        this.setUpShop();   
    }
    
    public void setUpShop(){
        // Every panel object in the shop must be able to access the products and shop hashmap
        
        fieldsAddProduct1.setProductMap(allProducts); // The objects needs to access the hashmap of products when we add new products.
        fieldsRegisterShop1.setShopHashMap(allShops); //The register tab needs to access the hashmap of shops.
        
        fieldsRegisterShop1.setUser(user);
    }
    
    public void setProductMap(HashMap<String, HashMap<String, ProductDTO>> allProducts){
        this.allProducts = allProducts;
        
    }
    public void setShopHashMap(HashMap<String,ShopDTO> allShops){
        this.allShops = allShops;
    }
    public void setUser(UserDTO user){
        this.user = user;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    
    public void overviewTab(){
        tabs.setSelectedIndex(0);
    }
    public void productsTab(){
        tabs.setSelectedIndex(1);
        panelMyProducts1.clear();
        panelMyProducts1.setup(db, allProducts, allShops, user,shop);
    }
    
    public void purchasesTab(){
        tabs.setSelectedIndex(2);
    }
    
    public void profileTab(){
        tabs.setSelectedIndex(3);
    }
    
    public void addProductTab(){
        tabs.setSelectedIndex(4);
    }
    
    public void setAddProduct(Dashboard db){
        fieldsAddProduct1.setDB(db);
        
    }
    
    public void setShop(ShopDTO shop){
        this.shop = shop;
    }
    
    public void setDB(Dashboard db){
        this.db = db;
        fieldsAddProduct1.setDB(db);
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar1 = new thrifty.Sidebar();
        jPanel1 = new javax.swing.JPanel();
        tabs = new javax.swing.JTabbedPane();
        panelOverview1 = new thrifty.shopUIs.PanelOverview();
        panelMyProducts1 = new thrifty.shopUIs.PanelMyProducts();
        purchases1 = new thrifty.shopUIs.Purchases();
        sPInfo1 = new thrifty.shopUIs.SPInfo();
        fieldsAddProduct1 = new thrifty.shopUIs.FieldsAddProduct();
        fieldsRegisterShop1 = new thrifty.shopUIs.FieldsRegisterShop();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1280, 800));
        setPreferredSize(new java.awt.Dimension(1280, 688));
        setLayout(new java.awt.BorderLayout());
        add(sidebar1, java.awt.BorderLayout.WEST);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabs.setBackground(new java.awt.Color(255, 255, 255));
        tabs.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        tabs.addTab("tab6", panelOverview1);
        tabs.addTab("tab4", panelMyProducts1);
        tabs.addTab("tab2", purchases1);
        tabs.addTab("tab5", sPInfo1);
        tabs.addTab("tab2", fieldsAddProduct1);
        tabs.addTab("tab6", fieldsRegisterShop1);

        tabs.setSelectedIndex(0);

        jPanel1.add(tabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 1160, -1));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private thrifty.shopUIs.FieldsAddProduct fieldsAddProduct1;
    private thrifty.shopUIs.FieldsRegisterShop fieldsRegisterShop1;
    private javax.swing.JPanel jPanel1;
    private thrifty.shopUIs.PanelMyProducts panelMyProducts1;
    private thrifty.shopUIs.PanelOverview panelOverview1;
    private thrifty.shopUIs.Purchases purchases1;
    private thrifty.shopUIs.SPInfo sPInfo1;
    private thrifty.Sidebar sidebar1;
    public javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables

}
