/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package thrifty.shopUIs;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import thrifty.Dashboard;
import thrifty.ProductDTO;

/**
 *
 * @author User
 */
public class MyProductItems extends javax.swing.JPanel {

    /**
     * Creates new form MyProductItems
     */
    String name;
    String image;
    String quantity;
    String dateAdded;
    String purchases;
    String price;
    Dashboard db;
    String productID;
    String description;
    ProductDTO product;
    
    
    public MyProductItems() {
        initComponents();
    }
    public static void icon(String path, JLabel component,int width, int height){
        ImageIcon imageIcon =  new ImageIcon(path);
        Image img = imageIcon.getImage();
        Image imageScaled = img.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(imageScaled);
        component.setIcon(scaledIcon);
        
    }
    public MyProductItems(String name, String image, int quantity, String dateAdded,int purchases, double price,Dashboard db,String productID,String description,ProductDTO product) {
        
        initComponents();
        this.name = name;
        this.image = image;
        String temp1 = String.valueOf(quantity);
        this.quantity = temp1;
        this.dateAdded = dateAdded;
        String temp2 = String.valueOf(purchases);
        this.purchases = temp2;
        String temp3 = String.valueOf(price);
        this.price = temp3;
        this.db = db;
        this.productID = productID;
        this.description = description;
        this.product = product;
        
        icon(image,imageLabel,45,45);
        nameLabel.setText(name);
        priceLabel.setText(this.price);
        quantityLabel.setText(this.quantity);
       
        purchasesLabel.setText(this.purchases);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        purchasesLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(1005, 83));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        imageLabel.setBackground(new java.awt.Color(255, 255, 255));
        imageLabel.setPreferredSize(new java.awt.Dimension(45, 45));

        nameLabel.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        nameLabel.setText("product name");

        priceLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        priceLabel.setText("PHP x");

        purchasesLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        purchasesLabel.setText("x");

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/thrifty/resources/delete.png"))); // NOI18N
        deleteButton.setPreferredSize(new java.awt.Dimension(50, 50));
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });

        quantityLabel.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        quantityLabel.setText("quan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(quantityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(purchasesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(priceLabel)
                            .addComponent(purchasesLabel)
                            .addComponent(quantityLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        //public FieldsEditProduct(String productID, String productName,String price,String quantity, String description, String picturePath,Dashboard db){
        FieldsEditProduct edit = new FieldsEditProduct(productID,name,price,quantity,description,image,db);
        db.editProduct(edit);
    }//GEN-LAST:event_formMouseClicked

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        // TODO add your handling code here:
        
        if (JOptionPane.showConfirmDialog(db, "Are you sure you want to delete?", "Confirm", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            db.deleteProduct(productID, product);
        }else{
            
        }
        
    }//GEN-LAST:event_deleteButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deleteButton;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel purchasesLabel;
    private javax.swing.JLabel quantityLabel;
    // End of variables declaration//GEN-END:variables
}
