/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package thrifty.shopUIs;

import java.util.HashMap;
import thrifty.Dashboard;
import thrifty.OrderDTO;
import thrifty.ProductDTO;
import thrifty.ShopDTO;
import thrifty.SoldItemDTO;
import thrifty.UserDTO;

/**
 *
 * @author User
 */
public class PanelMyProducts extends javax.swing.JPanel {

    /**
     * Creates new form PanelMyProducts
     */
    ShopDTO shop;
    public HashMap<String, HashMap<String, ProductDTO>> allProducts;
    public HashMap<String,ShopDTO> allShops;
    public HashMap<String,UserDTO> allUsers;
    public HashMap<String,OrderDTO> orders;
    Dashboard db;
    UserDTO user;
    
    public PanelMyProducts() {
        initComponents();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        scrollPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel1.setText("My Products");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setText("Product Name");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel3.setText("Unit Price");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel4.setText("Quantity");

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel7.setText("Purchases");

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel8.setText("Actions");

        scroll.setBackground(new java.awt.Color(255, 255, 255));
        scroll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        scroll.setPreferredSize(new java.awt.Dimension(1042, 500));

        scrollPanel.setBackground(new java.awt.Color(255, 255, 255));
        scrollPanel.setMinimumSize(new java.awt.Dimension(1030, 93));
        scrollPanel.setPreferredSize(new java.awt.Dimension(1030, 1000));
        scroll.setViewportView(scrollPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scroll, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel4)
                        .addGap(108, 108, 108)
                        .addComponent(jLabel7)
                        .addGap(79, 79, 79)
                        .addComponent(jLabel8)
                        .addGap(10, 10, 10)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void setShop(ShopDTO shop){
        this.shop = shop;
    }
    
    public void setDB(Dashboard db){
        this.db = db;
    }
    
    public void setup(Dashboard db,HashMap<String, HashMap<String, ProductDTO>> allProducts,HashMap<String,ShopDTO> allShops, UserDTO user, ShopDTO shop){
        this.db = db;
        this.allProducts = allProducts;
        this.allShops = allShops;
        this.user = user;
        this.shop = shop;
        
        this.createProduct();
        
    }
    
    public void createProduct(){
        int purchases = 0;
        HashMap<String, ProductDTO> flattenedProducts = new HashMap<>();
        
        for (HashMap<String, ProductDTO> innerMap : db.getallProducts().values()) {
            flattenedProducts.putAll(innerMap);
        }
        
        
        
        for (String productID: db.getUserShop().getProducts()){
            purchases = 0;
            ProductDTO product = flattenedProducts.get(productID);
            // public MyProductItems(String name, String image, int quantity, String dateAdded,int purchases, double price)
            for(String key : db.getSoldItems().keySet()){
                
                SoldItemDTO soldItem = db.getSoldItems().get(key);
                String soldItemPID = soldItem.getProductID();
                if(soldItemPID.equals(productID)){
                    purchases += soldItem.getQuantitySold();
                }
            }
            MyProductItems newItem = new MyProductItems(product.getName(),product.getImage(),product.getQuantity(), "NA",purchases,product.getPrice(),db,productID,product.getDescription(),product);
            scrollPanel.add(newItem);
        }
    }
    
    public void clear(){
        scrollPanel.removeAll();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JPanel scrollPanel;
    // End of variables declaration//GEN-END:variables
}
