/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package thrifty.shopUIs;

import java.awt.Component;
import java.util.ArrayList;
import java.util.HashMap;
import thrifty.Dashboard;
import thrifty.OrderDTO;
import thrifty.ProductDTO;
import thrifty.ShopDTO;
import thrifty.UserDTO;

/**
 *
 * @author User
 */
public class Purchases extends javax.swing.JPanel {
    ShopDTO shop;
    Dashboard db;
    HashMap<String,ShopDTO> allShops;
    HashMap<String,OrderDTO> orders;
    HashMap<String,UserDTO> allUsers;
    /**
     * Creates new form PanelMyProducts
     */
    public Purchases() {
        initComponents();
    }
    public void setShop(ShopDTO shop){
        this.shop = shop;
    }
    public void clear(){
        scrollPanel.removeAll();
    }
    public void setup(Dashboard db){
        this.db = db;
        
        allShops = db.getShop();
        shop = db.getUserShop();
        orders = db.getOrder();
        allUsers = db.getUserFiles();
        ArrayList<String> shopOrders = shop.getOrders();
        
        for (String orderID: shopOrders){
            System.out.println(orderID);
            //public PurchasesItem(String productName, String date,String customerName,String quantity,String price, String totalPrice)
            String customerName = allUsers.get(orders.get(orderID).getBuyerID()).getName();
            String productName = orders.get(orderID).getProduct().getName();
            String date = orders.get(orderID).getDateBought();
            String quantity = String.valueOf(orders.get(orderID).getQuantitySold());
            String price = orders.get(orderID).getPrice();
            String totalPrice = String.valueOf(orders.get(orderID).getTotalPrice());
            ProductDTO product = orders.get(orderID).getProduct();
            UserDTO buyer = allUsers.get(orders.get(orderID).getBuyerID());
            
            
            PurchasesItem item = new PurchasesItem(productName,date,customerName,quantity,price,totalPrice,db,orderID,product,buyer,shop,this);
            scrollPanel.add(item);
        }
        
        
    }
    public void removePurchase(Component purchase){
        scrollPanel.remove(purchase);
        
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        scroll = new javax.swing.JScrollPane();
        scrollPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel1.setText("Purchases");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel2.setText("Date Purchased");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel3.setText("Product Name");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel4.setText("Customer");

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel6.setText("Quantity");

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel7.setText("Unit Price");

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel8.setText("Actions");

        scroll.setBackground(new java.awt.Color(255, 255, 255));
        scroll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        scrollPanel.setBackground(new java.awt.Color(255, 255, 255));
        scrollPanel.setPreferredSize(new java.awt.Dimension(1038, 10));
        scroll.setViewportView(scrollPanel);

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel9.setText("Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel3)
                        .addGap(107, 107, 107)
                        .addComponent(jLabel4)
                        .addGap(114, 114, 114)
                        .addComponent(jLabel6)
                        .addGap(71, 71, 71)
                        .addComponent(jLabel7)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 1038, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JPanel scrollPanel;
    // End of variables declaration//GEN-END:variables
}
