/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package thrifty.shopUIs;

/**
 *
 * @author User
 */
public class SellLogItems extends javax.swing.JPanel {

    /**
     * Creates new form SellLogItems
     */
    public SellLogItems() {
        initComponents();
    }
    
     public SellLogItems(String productName, String customerName, double unitPrice, int quantity, double totalPrice, String date) {
        initComponents();
        productNameLabel.setText(productName);
        customerNameLabel.setText(customerName);
        String tempUnitPrice = String.valueOf(unitPrice);
        priceLabel.setText(tempUnitPrice);
        totalPriceLabel.setText(String.valueOf(totalPrice));
        dateLabel.setText(date);
        quantityLabel.setText(String.valueOf(quantity));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        productNameLabel = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        totalPriceLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(1000, 35));

        productNameLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        productNameLabel.setText("product name");

        customerNameLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        customerNameLabel.setText("customer name");

        priceLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        priceLabel.setText("unit price");

        quantityLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        quantityLabel.setText("qty");

        totalPriceLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        totalPriceLabel.setText("total PRice");

        dateLabel.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        dateLabel.setText("date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(productNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(customerNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(quantityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productNameLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dateLabel)
                        .addComponent(totalPriceLabel)
                        .addComponent(quantityLabel)
                        .addComponent(priceLabel)
                        .addComponent(customerNameLabel)))
                .addGap(7, 7, 7))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel productNameLabel;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JLabel totalPriceLabel;
    // End of variables declaration//GEN-END:variables
}
